# Generated by Django 6.0.3 on 2026-08-04 23:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiarioCadete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('dinero_sobrante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('viajes', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cadete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='gestion.cadete')),
            ],
            options={
                'verbose_name': 'Registro Diario de Cadete',
                'verbose_name_plural': 'Registros Diarios de Cadetes',
                'unique_together': {('cadete', 'fecha')},
            },
        ),
    ]
